networks:
  terragon-network:
    driver: bridge
services:
  causal-interface-gym:
    build:
      context: .
      dockerfile: Dockerfile.production
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
    - ENV=production
    - LOG_LEVEL=info
    - PROMETHEUS_PORT=9090
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      timeout: 10s
    ports:
    - 8000:8000
  grafana:
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=secure_password_change_me
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - grafana-storage:/var/lib/grafana
  nginx:
    depends_on:
    - causal-interface-gym
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/production.conf:/etc/nginx/nginx.conf:ro
    - ./ssl:/etc/nginx/ssl:ro
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
version: '3.8'
volumes:
  grafana-storage: {}
