alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- alert.rules.yml
scrape_configs:
- job_name: causal-interface-gym
  metrics_path: /metrics
  scrape_interval: 15s
  static_configs:
  - targets:
    - causal-interface-gym:8000
