apiVersion: apps/v1
kind: Deployment
metadata:
  name: causal-gym-api
  namespace: causal-gym
  labels:
    app: causal-gym-api
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: causal-gym-api
  template:
    metadata:
      labels:
        app: causal-gym-api
        version: v1
    spec:
      serviceAccountName: causal-gym
      containers:
      - name: causal-gym-api
        image: causal-interface-gym:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: CAUSAL_GYM_ENVIRONMENT
          value: "production"
        - name: CAUSAL_GYM_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: causal-gym-secrets
              key: database-url
        - name: CAUSAL_GYM_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: causal-gym-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-secrets
              key: anthropic-api-key
        - name: CAUSAL_GYM_LOG_LEVEL
          value: "INFO"
        - name: CAUSAL_GYM_STRUCTURED_LOGGING
          value: "true"
        - name: CAUSAL_GYM_MAX_CONCURRENT
          value: "20"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: data
          mountPath: /app/data
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: causal-gym-logs
      - name: data
        persistentVolumeClaim:
          claimName: causal-gym-data
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: "causal-gym"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: causal-gym-api-service
  namespace: causal-gym
  labels:
    app: causal-gym-api
spec:
  selector:
    app: causal-gym-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: causal-gym-ingress
  namespace: causal-gym
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
  - hosts:
    - api.causal-gym.com
    secretName: causal-gym-tls
  rules:
  - host: api.causal-gym.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: causal-gym-api-service
            port:
              number: 8000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: causal-gym-logs
  namespace: causal-gym
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: causal-gym-data
  namespace: causal-gym
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: causal-gym-pdb
  namespace: causal-gym
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: causal-gym-api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: causal-gym-hpa
  namespace: causal-gym
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: causal-gym-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15