jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./Dockerfile.production
        push: true
        tags: terragon/causal-interface-gym:latest
    - name: Deploy to production
      run: kubectl apply -f k8s/production-*.yaml
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -e ".[dev]"
    - name: Run quality gates
      run: python scripts/quality_gates_runner.py
    - name: Run security scan
      run: bandit -r src/
name: Terragon Production Deploy
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
